### ISSUE TITLE
Missing signal.SIGHUP on windows breaks logging to file

### ISSUE THREAD

**Issue by prkHack** [krig/send_arp.py#2]
Hi,

I found the "logging to file" to be broken while running python on windows machine. An explanation follows.

It works fine under Linux but unfortunately there is a limitation using windows, which I found in the python docs
https://docs.python.org/2/library/signal.html#signal.signal 

> On Windows, signal() can only be called with SIGABRT, SIGFPE, SIGILL, SIGSEGV, or SIGTERM. 
>      A ValueError will be raised in any other case.

This is the error produced:

> Traceback (most recent call last):
>   File "send_arp.py", line 185, in <module>
>     main()
>   File "send_arp.py", line 156, in main
>     setup_pid_file(args.pidfile)
>   File "send_arp.py", line 148, in setup_pid_file
>     for sig in [signal.SIGTERM, signal.SIGINT, signal.SIGHUP, signal.SIGQUIT]:
> AttributeError: 'module' object has no attribute 'SIGHUP'

Thus, currently no file logging is possible under windows. (at least I found no way to do it)

What can be done to solve this problem? OS Detection?

Thank you very much for your help!

**Comment by krig** [comment]
Hi! Yeah, I guess the only solution is to have separate lists of signals for windows and POSIX systems.
